Error messages for the contract validations show code/no validation message
gnosis/conditional-tokens-explorer pull request #271
Opened 2020-09-16 15:57 UTC by davidalbela

Closes #223 

- [x] Reduce message error from CustomCollateralModal for SplitPosition page.
- [ ] No validation message about unsuccessful attempt of unlocking an account.

2020-09-16 16:03 UTC, gnosis-info commented
Travis automatic deployment:
 https://pr271--conditionaltokensexplorer.review.gnosisdev.com

2020-09-16 16:16 UTC, gnosis-info commented
Travis automatic deployment:
 https://pr271--conditionaltokensexplorer.review.gnosisdev.com

2020-09-17 16:38 UTC, mariano-aguero commented
Hi @davidalbela is this already done ? I see a task not checked, can you confirm ? thanks in advance

2020-09-18 08:41 UTC, davidalbela commented
> Hi @davidalbela is this already done ? I see a task not checked, can you confirm ? thanks in advance

I would like to add the validation message before merge, thanks to you!

2020-09-18 17:34 UTC, mariano-aguero commented
The second error 
```
No validation message about unsuccessful attempt of unlocking an account (see the video)
https://drive.google.com/file/d/1kiGBF0UK4GaG6wDyXEEYXKZwF65DgOoT/view
```
seems to be already fixed in the develop branch, just a clarification..

2020-09-18 17:35 UTC, mariano-aguero commented on src/hooks/useCollateral.tsx
> +            err.message = err.message.split('(')[0]
Could you capitalize the first letter? Thank you

2020-09-18 17:35 UTC, mariano-aguero reviewed
See comments

2020-09-18 18:41 UTC, hpmaxi requested changes
Maybe some errors don't have a '(', or this changes in the future. Maybe you can add some function in `utils` that search for some patterns in the error.message or error.reason and return constant values likes the ones in `types.ts`, and default to something generic (and maybe logging that is and special case so we can handle it in future changes).

2020-09-21 08:42 UTC, elena-zh commented
The 2nd issue seems to be unfixed now. 
I expected here to get a validation message something like 'MetaMask Tx Signature: User denied transaction signature.' or so. 
However, there is another task exists that is related to the Unlock contract section -  #280. 
I think that it will be possible to fix the 2nd case under the new task and show an error message when a user rejects transaction in Metamask or any other connected app.

2020-09-22 11:50 UTC, gnosis-info commented
Travis automatic deployment:
 https://pr271--conditionaltokensexplorer.review.gnosisdev.com

2020-09-22 15:05 UTC, mariano-aguero commented
@davidalbela any updates on the second error ?

2020-09-22 16:12 UTC, hpmaxi approved these changes

2020-09-22 16:24 UTC, mariano-aguero approved these changes

2020-09-23 09:34 UTC, davidalbela commented
Can I refactor `getTokenSummary` method?

2020-09-23 10:06 UTC, gnosis-info commented
Travis automatic deployment:
 https://pr271--conditionaltokensexplorer.review.gnosisdev.com

2020-09-23 12:08 UTC, merged

2020-09-23 12:24 UTC, elena-zh commented
Verified. 

The 1st case is fixed. 
As for the 2nd case: currently, there is no error message/unlock section does not change its state the error state https://zpl.io/aXeP0QE when a user rejects the unlock transaction in Metamask. The section returns to its 'Unlock' default view.
@mariano-aguero , could you please confirm that we should leave it as it is?

2020-09-24 08:33 UTC, davidalbela commented
@elena-zh @mariano-aguero I will create other PR for 2nd case