Allow to wrap/unwrap collateral
gnosis/conditional-tokens-explorer pull request #303
Opened 2020-09-22 13:01 UTC by mariano-aguero

Closes #187 
Closes #194 
Closes #190 
Closes #204 
Closes #188 
Closes #189 

This PR will allow to wrap/unwrapp collateral in position list section, and the position details section.

NOTE: The  transaction work with newly created condition/positions (unless a new update change this behavior)
The PR probably will not work,because we need to put some new env vars to the preview, so check this locally

2020-09-22 13:02 UTC, mariano-aguero commented on scripts/generateGQLTypes.js
>    err => {
Changed to rinkeby, because the mainnet subgraph is not updated

2020-09-22 13:05 UTC, gnosis-info commented
Travis automatic deployment:
 https://pr303--conditionaltokensexplorer.review.gnosisdev.com

2020-09-22 16:11 UTC, gnosis-info commented
Travis automatic deployment:
 https://pr303--conditionaltokensexplorer.review.gnosisdev.com

2020-09-22 18:14 UTC, gabitoesmiapodo requested changes
Seems to work fine overall. I just found a few issues:

- If I wrap `10` ERC1155 (DAI) everything is fine, I get `10` WMT ERC20. The same goes for most tokens.
- But if I wrap `6.66` ERC1155 (USDC), I get `0.00000000000666` WMT ERC20.
- And if I wrap `3.32` ER1155 ([WBTC](https://rinkeby.etherscan.io/token/0x577d296678535e4903d59a4c929b718e1d575e0a)), I get `0.000000000332` WMT ERC20.

I guess it has something to do with decimals of precision.

2020-09-22 18:20 UTC, hpmaxi commented on src/hooks/useCollateral.tsx
> +          }
loading and error never changes.

2020-09-22 18:22 UTC, hpmaxi approved these changes

2020-09-22 20:45 UTC, gnosis-info commented
Travis automatic deployment:
 https://pr303--conditionaltokensexplorer.review.gnosisdev.com

2020-09-23 12:45 UTC, gnosis-info commented
Travis automatic deployment:
 https://pr303--conditionaltokensexplorer.review.gnosisdev.com

2020-09-23 12:52 UTC, gabitoesmiapodo approved these changes

2020-09-23 12:53 UTC, merged