Modal pages
gnosis/conditional-tokens-explorer pull request #306
Opened 2020-09-22 15:17 UTC by hpmaxi

2020-09-22 15:18 UTC, hpmaxi commented on src/pages/MergePositions/Contents.tsx
> +        }
This should check for partial merges.

2020-09-22 15:21 UTC, gnosis-info commented
Travis automatic deployment:
 https://pr306--conditionaltokensexplorer.review.gnosisdev.com

2020-09-22 16:23 UTC, gnosis-info commented
Travis automatic deployment:
 https://pr306--conditionaltokensexplorer.review.gnosisdev.com

2020-09-22 18:59 UTC, gabitoesmiapodo requested changes
For "Report Payouts" you are showing this (a modal) when finished:

![Screen Shot 2020-09-22 at 15 20 56](https://user-images.githubusercontent.com/4015436/93922402-3b8e1180-fce8-11ea-80ad-439998e918da.png)

But it should look like this ("FullLoading" component, not a modal, you should obviously change the wording), you can grab some code from _"Transfer Outcome Tokens":_

![Screen Shot 2020-09-22 at 15 28 35](https://user-images.githubusercontent.com/4015436/93922533-71cb9100-fce8-11ea-8279-954b691c71b9.png)

----

Same here ("Redeem Positions"):

![Screen Shot 2020-09-22 at 15 36 21](https://user-images.githubusercontent.com/4015436/93923221-7775a680-fce9-11ea-97a8-3f23ed2fb3a6.png)

----

For "Merge Positions" you are showing a modal like this:

![Screen Shot 2020-09-22 at 15 45 42](https://user-images.githubusercontent.com/4015436/93924372-046d2f80-fceb-11ea-9964-0161dca2beac.png)

... which is fine, but you should be showing more info, like what we have for "Split Position"'s result:

![Screen Shot 2020-09-22 at 15 50 56](https://user-images.githubusercontent.com/4015436/93924687-75ace280-fceb-11ea-9c83-122d7f53454f.png)

Keep in mind that you should use a "FullLoading" component in case there's an error though.

----

Regarding the "FullLoading" components, generally speaking the format should be:

- **Title:** Merge Positions / Report Payouts / Redeem Positions
- **Icon:** Whatever the status is (Error / Success).
- **Text:** "Working..." if working / "All done!" or "Finished!" when finished / "There was an error." or the full error string if available.
- Green "OK" button for success, red "Close" button for errors.

2020-09-23 20:23 UTC, gnosis-info commented
Travis automatic deployment:
 https://pr306--conditionaltokensexplorer.review.gnosisdev.com

2020-09-23 20:39 UTC, hpmaxi commented
I've updated the original description and it's working for partial merging too.

2020-09-24 12:53 UTC, mariano-aguero approved these changes
There are a lot of details that we can work in another issue, @gabitoesmiapodo will create it

2020-09-24 12:55 UTC, gabitoesmiapodo approved these changes
Good enough, but it needs a little work to achieve greatness.

I will create a few issues so we can achieve it.

2020-09-24 12:55 UTC, merged