(Fix) Status info consistency issues
gnosis/conditional-tokens-explorer pull request #442
Opened 2020-10-07 21:13 UTC by gabitoesmiapodo

Closes #342

Not adding screenshots because it's a lot of extra work, but the status info modal windows all should look as requested now.

2020-10-07 21:17 UTC, gnosis-info commented
Travis automatic deployment:
 https://pr442--conditionaltokensexplorer.review.gnosisdev.com

2020-10-08 00:56 UTC, gnosis-info commented
Travis automatic deployment:
 https://pr442--conditionaltokensexplorer.review.gnosisdev.com

2020-10-08 01:47 UTC, gnosis-info commented
Travis automatic deployment:
 https://pr442--conditionaltokensexplorer.review.gnosisdev.com

2020-10-08 02:06 UTC, gnosis-info commented
Travis automatic deployment:
 https://pr442--conditionaltokensexplorer.review.gnosisdev.com

2020-10-08 02:24 UTC, gnosis-info commented
Travis automatic deployment:
 https://pr442--conditionaltokensexplorer.review.gnosisdev.com

2020-10-08 16:01 UTC, hpmaxi requested changes

2020-10-08 16:38 UTC, gabitoesmiapodo commented on src/components/text/FormatHash/index.tsx
> +
I don't think it should affect anything, it's only used to display addresses.

2020-10-08 16:40 UTC, gnosis-info commented
Travis automatic deployment:
 https://pr442--conditionaltokensexplorer.review.gnosisdev.com

2020-10-08 16:57 UTC, hpmaxi approved these changes

2020-10-08 20:18 UTC, mariano-aguero approved these changes

2020-10-08 20:18 UTC, merged