Call checkValidity and provide min-max parameters
gnosis/conditional-tokens-explorer pull request #491
Opened 2020-10-19 17:20 UTC by hpmaxi

Closes #434

The same problem was in the filters. For prepare condition the min date is set to today.

2020-10-19 17:23 UTC, hpmaxi commented on src/pages/PrepareCondition/index.tsx
> +                            'Invalid date or out of range'
Is not the same message as in filters ...  I should unify them after review.

2020-10-19 17:25 UTC, gnosis-info commented
Travis automatic deployment:
 https://pr491--conditionaltokensexplorer.review.gnosisdev.com

2020-10-19 20:23 UTC, gabitoesmiapodo requested changes
It works, but I'd suggest that you let the user know which are the min and max valid dates.

For example, for the filters: if the user manually enters and invalid minimum date, use something like "Minimum 'From' date is `so and so`". And do the same for the maximum date.

For "Prepare Condition" it could be simpler: "Valid dates are from today (`date here`) to `maximum date`)."

We shouldn't keep the user guessing.

2020-10-19 20:41 UTC, gnosis-info commented
Travis automatic deployment:
 https://pr491--conditionaltokensexplorer.review.gnosisdev.com

2020-10-20 07:17 UTC, elena-zh commented
@hpmaxi , 
I also have reviewed the changes. 
Everything works as expected in calendar filters in the Condition details page. However, some issues are still reproducible on the Prepare condition page: 
- no validation when a date in the past and when a date is incorrect. Actually, validation message appears in a certain cases, and then disappears https://drive.google.com/file/d/1vCQrZpfw6f32UmZ1ZAROqn3SHpc4H1mo/view
-the same with the date in the future: sometimes I am able to see the validation message, sometimes - not
![future](https://user-images.githubusercontent.com/70885163/96553180-74a4ac00-12bd-11eb-91ce-ce2c386734a3.jpg)

Please, take a look into these issues

2020-10-20 13:47 UTC, mariano-aguero approved these changes

2020-10-20 13:48 UTC, mariano-aguero commented
@hpmaxi fix the issue that Elena reported. Feel free to merge after that

2020-10-20 15:17 UTC, gabitoesmiapodo approved these changes
Fix is OK. I'd probably go with a shorter message, and we probably should use the same format in the input field and the error message though.

Nevermind, I'll change it later.

2020-10-20 16:36 UTC, merged

2020-10-21 08:54 UTC, elena-zh commented
Verified. 
Notes are [here](https://github.com/gnosis/conditional-tokens-explorer/issues/434#issuecomment-713416553)