Omen markets details
gnosis/conditional-tokens-explorer pull request #595
Opened 2020-11-10 18:47 UTC by hpmaxi

Closes #356 

This can be tested now but I'm still working on fetching markets for all possible conditions related to the condition/position. An array is passed to a custom component to be used in any component but in his logic in only passes to the query the first one.

2020-11-10 18:55 UTC, gnosis-info commented
Travis automatic deployment:
 https://pr595--conditionaltokensexplorer.review.gnosisdev.com

2020-11-11 17:22 UTC, gabitoesmiapodo requested changes
I know the "design" says otherwise, but it would probably make more sense having the link to the market in the question for the Condition Details. Otherwise you'll have two items which are basically the same:

```
Question
Question text

Omen Market 
Question text [link]
```

I think it makes more sense having only:

```
Question
Question text [link]
```


Also: should this field be shown on the position details section? I'm asking because I couldn't find any.

In case it also belongs to the position details section, I think the `Omen Market: Question text [link]` format would be OK.

2020-11-12 00:37 UTC, hpmaxi commented
@gabitoesmiapodo I think that is possible to have a position (from the list of positions of a condition with omen markets) that has a related condition with omen markets. But the problem is that 1 condition could be related to many markets, and a position with depth > 1 could have more than one condition (N), each with one or more markets (M), so is something like NxM markets listed in the position detail.

2020-11-12 01:05 UTC, gabitoesmiapodo commented
@hpmaxi Yeah... I'm not sure I understood anything you said, but in case I did: if you can't put that info in a Position Details section for whatever reason (or if it's incredibly complicated), just don't.

I'm just asking because https://github.com/gnosis/conditional-tokens-explorer/issues/356 mentions something about positions ("(...) any omen markets that have been created for a position and link out to them.").

The issue about the Condition Details sections `Question / Omen Market` info still stands, though.

2020-11-12 15:52 UTC, gnosis-info commented
Travis automatic deployment:
 https://pr595--conditionaltokensexplorer.review.gnosisdev.com

2020-11-12 16:04 UTC, hpmaxi commented on src/components/form/DisplayTableHashes/index.tsx
> +          } else {
This is the hacky part of the PR, I can't use the hash as a title but at the same time I need the hash to get the url.

2020-11-12 16:04 UTC, hpmaxi commented on src/hooks/useOmenMarkets.tsx
> +            })
This has a lot of types and type guards to shape the data in a way more convenient for the consumer component.

2020-11-12 20:15 UTC, mariano-aguero approved these changes

2020-11-12 20:26 UTC, mariano-aguero commented
@hpmaxi I give my approve, but let check gabriel feedback and the possible question in the channel

2020-11-13 13:53 UTC, hpmaxi commented
@auryn-macmillan What do you think about the preview of this one, you can view it here `https://pr595--conditionaltokensexplorer.review.gnosisdev.com/#/conditions/0x1e33c1fc428f35eeef468623bf773b20c6c24f591b491735f092b6410a2d5f95`, and on the positions listed for that condition.

We have, only for conditions details, two sections very similar. One is the question that is only shown if it is an omen condition, that just interpret the `questionId` used in his creation as a Reality.eth entity, and the other is the `Omen Markets` section that search in the omen subgraph for conditions and his `fpmm`, and then extract the non-empty question `fpmm`.

We should try to unify this to only one section?

2020-11-13 16:12 UTC, auryn-macmillan commented
> We should try to unify this to only one section?
Yes, I don't think there is any need to duplicate the question text.

For positions, it would be great to also show the text of the outcome(s) that correspond with the position.

2020-11-13 20:02 UTC, gnosis-info commented
Travis automatic deployment:
 https://pr595--conditionaltokensexplorer.review.gnosisdev.com

2020-11-16 15:10 UTC, gabitoesmiapodo requested changes
It looks better but:

- We still should show the question when there are not markets for the condition.
- We should show something while the markets are being fetched. What we usually do is: Show the title (Omen Markets) and `-` for contents (or it could be `Loading...`). Once markets are fetched, replace the contents.

2020-11-16 15:58 UTC, gabitoesmiapodo commented
@hpmaxi please also take a look at this https://app.zenhub.com/workspaces/conditional-tokens-explorer-5eecb9b75ab924001c8aa224/issues/gnosis/conditional-tokens-explorer/621

2020-11-16 18:28 UTC, gnosis-info commented
Travis automatic deployment:
 https://pr595--conditionaltokensexplorer.review.gnosisdev.com

2020-11-16 18:57 UTC, gnosis-info commented
Travis automatic deployment:
 https://pr595--conditionaltokensexplorer.review.gnosisdev.com

2020-11-16 20:11 UTC, gnosis-info commented
Travis automatic deployment:
 https://pr595--conditionaltokensexplorer.review.gnosisdev.com

2020-11-17 13:43 UTC, gabitoesmiapodo approved these changes

2020-11-17 13:43 UTC, merged

2020-11-17 13:46 UTC, gnosis-info commented
Travis automatic deployment:
 https://pr595--conditionaltokensexplorer.review.gnosisdev.com

2020-11-18 10:36 UTC, elena-zh commented
Verified and LGTM (along with #621 and #622). 
Some more related UI issues are found and reported in #627