Add a loader when REDEEMED POSITION PREVIEW is loaded
gnosis/conditional-tokens-explorer pull request #743
Opened 2020-12-04 13:51 UTC by mariano-aguero

Closes #742

2020-12-04 13:55 UTC, gnosis-info commented
Travis automatic deployment:
 https://pr743--conditionaltokensexplorer.review.gnosisdev.com

2020-12-04 15:16 UTC, hpmaxi requested changes

2020-12-04 15:16 UTC, hpmaxi commented on src/components/redeemPosition/PositionPreview/index.tsx
>    const { balanceERC1155, refetch } = useBalanceForPosition(position?.id || '')
This could have a loading too?

2020-12-14 13:11 UTC, elena-zh commented
The changes LGTM (from the UI side).

2020-12-14 13:55 UTC, gnosis-info commented
Travis automatic deployment:
 https://pr743--conditionaltokensexplorer.review.gnosisdev.com

2020-12-14 14:00 UTC, gabitoesmiapodo commented
Fixed a little height / jumping issue with the spinner / preview container.

Otherwise, this looks good.

2020-12-16 15:51 UTC, mariano-aguero commented on src/components/redeemPosition/PositionPreview/index.tsx
>    const { balanceERC1155, refetch } = useBalanceForPosition(position?.id || '')
Sure

2020-12-16 16:02 UTC, hpmaxi approved these changes

2020-12-16 17:11 UTC, merged